# Generated by Django 4.2.7 on 2024-01-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="name",
            new_name="rec_first_name",
        ),
        migrations.AddField(
            model_name="company",
            name="company_contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="company_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="current_company_location",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="rec_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
