# Generated by Django 4.2.7 on 2024-01-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_rename_name_company_rec_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_email_id",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
