# Generated by Django 4.2.7 on 2023-11-26 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                            ("Pending", "Pending"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("salary", models.PositiveIntegerField(default=35000)),
                ("requirements", models.TextField()),
                ("ideal_candidate", models.TextField()),
                ("is_available", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Remote", "Remote"),
                            ("Onsite", "Onsite"),
                            ("Hybrid", "Hybrid"),
                            ("Full-Time", "Full-Time"),
                            ("Part-Time", "Part-Time"),
                            ("Temporary", "Temporary"),
                            ("Freelance", "Freelance"),
                            ("Internships", "Internships"),
                            ("Apprenticeships", "Apprenticeships"),
                            ("Shift Work", "Shift Work"),
                            ("Volunteer Work", "Volunteer Work"),
                            ("Entry-Level", "Entry-Level"),
                            ("Executive", "Executive"),
                            ("Commission-Based", "Commission-Based"),
                            ("Consulting", "Consulting"),
                            ("Permanent", "Permanent"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="job.industry",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="job.state",
                    ),
                ),
            ],
        ),
    ]
