# Generated by Django 4.2.7 on 2024-01-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_alter_job_salary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="title",
            new_name="job_title",
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
