# Generated by Django 4.2.7 on 2024-01-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_rename_title_job_job_title_job_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
