# Generated by Django 4.2.7 on 2024-01-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "resume",
            "0004_resume_age_resume_city_resume_education_resume_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="resume",
            name="education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "High School"),
                    ("associate_degree", "Associate Degree"),
                    ("bachelor_degree", "Bachelor's Degree"),
                    ("master_degree", "Master's Degree"),
                    ("PhD", "PhD"),
                    ("other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.ManyToManyField(blank=True, to="resume.skill"),
        ),
    ]
