# Generated by Django 4.2.7 on 2024-01-11 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0005_skill_alter_resume_education_resume_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="skills",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
