# Generated by Django 4.2.7 on 2024-01-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0006_remove_resume_skills_delete_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
