# Generated by Django 4.2.7 on 2024-01-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0010_alter_resume_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
