# Generated by Django 4.2.7 on 2024-01-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0012_alter_resume_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
